export const environment = {
    production: false,
    forceNhlApiImport: false,
    forcePlayerImport: true,
    currentTeams: [
        {id: 24, franchiseId: 32, triCode: 'ANA'},
        {id: 53, franchiseId: 28, triCode: 'ARI'},
        {id: 6, franchiseId: 6, triCode: 'BOS'},
        {id: 7, franchiseId: 19, triCode: 'BUF'},
        {id: 20, franchiseId: 21, triCode: 'CGY'},
        {id: 12, franchiseId: 26, triCode: 'CAR'},
        {id: 16, franchiseId: 11, triCode: 'CHI'},
        {id: 21, franchiseId: 27, triCode: 'COL'},
        {id: 29, franchiseId: 36, triCode: 'CBJ'},
        {id: 25, franchiseId: 15, triCode: 'DAL'},
        {id: 17, franchiseId: 12, triCode: 'DET'},
        {id: 22, franchiseId: 25, triCode: 'EDM'},
        {id: 13, franchiseId: 33, triCode: 'FLA'},
        {id: 26, franchiseId: 14, triCode: 'LAK'},
        {id: 30, franchiseId: 37, triCode: 'MIN'},
        {id: 8, franchiseId: 1, triCode: 'MTL'},
        {id: 18, franchiseId: 34, triCode: 'NSH'},
        {id: 1, franchiseId: 23, triCode: 'NJD'},
        {id: 2, franchiseId: 22, triCode: 'NYI'},
        {id: 3, franchiseId: 10, triCode: 'NYR'},
        {id: 9, franchiseId: 30, triCode: 'OTT'},
        {id: 4, franchiseId: 16, triCode: 'PHI'},
        {id: 5, franchiseId: 17, triCode: 'PIT'},
        {id: 28, franchiseId: 29, triCode: 'SJS'},
        {id: 55, franchiseId: 39, triCode: 'SEA'},
        {id: 19, franchiseId: 18, triCode: 'STL'},
        {id: 14, franchiseId: 31, triCode: 'TBL'},
        {id: 10, franchiseId: 5, triCode: 'TOR'},
        {id: 23, franchiseId: 20, triCode: 'VAN'},
        {id: 54, franchiseId: 38, triCode: 'VGK'},
        {id: 15, franchiseId: 24, triCode: 'WSH'},
        {id: 52, franchiseId: 35, triCode: 'WPG'}
      ]
};
